### ISSUE TITLE
Add language to include VM Scale Sets

### ISSUE THREAD

**Issue by jwes2** [mspnp/elasticsearch#70]
Some of the language found in **Deploying Multiple instances of services** and **Use Availability Sets** feels a little stale with the introduction of Virtual Machine Scale sets. We should include mention of VM Scale Sets and link to https://azure.microsoft.com/en-us/services/virtual-machine-scale-sets/

**Comment by bennage** [comment]
Relocated to https://github.com/mspnp/architecture-center/issues/14
