### ISSUE TITLE
template validation issue on DeployElasticsearchClusterUbuntu.ps1

### ISSUE THREAD

**Issue by daniel-habib** [mspnp/elasticsearch#77]
the script keep failing on line
`Test-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroupName -TemplateUri $templateUri -TemplateParameterObject $parameters -Verbose`

the error message:
`Code    : InvalidTemplate
Message : Deployment template validation failed: 'The template parameters 'storageSettings' in the parameters file are
          not valid; they are not present in the original template and can therefore not be provided at deployment
          time. The only supported parameters for this template are 'subnet, storageAccountName, adminUsername,
          authSet, osSettings, vmSize, vmCount, lbBackendPools, marvelNodesIpPrefix, namespace'. Please see
          https://aka.ms/arm-deploy/#parameter-file for usage details.'.`

the params i provide:
`$parameters=@{
 adminUserName='user'
 adminPassword='password'
 virtualNetworkName='a-vnet'
 esClusterName='a-elasticsearch-cluster'
 loadBalancerType='external'
 vmSizeDataNodes='Standard_D2_v2'
 vmClientNodeCount=0
 vmDataNodeCount=3
 OS='ubuntu' 
 esVersion='2.2.2'
 marvel='yes'
 kibana='yes'
}`

I assumed that one of the templates in https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/elasticsearch/nestedtemplates was not expecting storageSettings - but they all seem to be in order.

have you ever encountered that?

Daniel

**Comment by jocontr** [comment]
Closing issue before archiving this repo.
